# Generated by Django 4.2.7 on 2024-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_product_image_url_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, related_name="product", to="shop.category"),
        ),
    ]
