# Generated by Django 4.2.7 on 2024-02-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="shop.shop"),
        ),
    ]
