# Generated by Django 4.2.7 on 2024-02-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_remove_category_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="User",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
